In [9]:
import numpy as np

arr1 = np.arange(15).reshape([5,3])
arr2 = np.arange(6).reshape([3,2])
dotArr = np.dot(arr1,arr2)
print(dotArr, dotArr.shape)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]] (5, 2)


In [10]:
import numpy as np

arr1 = [[5, 7], [9,11]]
arr2 = [[2, 4], [6,8]]

print(np.concatenate((arr1,arr2), axis=0), np.concatenate((arr1, arr2), axis=1))

[[ 5  7]
 [ 9 11]
 [ 2  4]
 [ 6  8]] [[ 5  7  2  4]
 [ 9 11  6  8]]


In [55]:
import pandas as pd

idx = ["HDD", "SSD", "USB", "CLOUD"]
data = [19, 11, 5, 97]

sr = pd.Series(data, idx)

sr1 = sr[sr > 10]
sr2 = sr1[sr1 <20]
print(sr2, '\n')

sr1 = sr.loc[lambda x: x > 10]
sr2 = sr1.loc[lambda x: x < 20]
print(sr2, '\n')

sr1 =sr.to_frame(name='x').query('x > 10 and x < 20')
print(sr1, '\n')

HDD    19
SSD    11
dtype: int64 

HDD    19
SSD    11
dtype: int64 

      x
HDD  19
SSD  11 



In [163]:
import pandas as pd

raw_data = {
    'NAME': ['cherry', 'mango', 'potato', 'onion'],
    'TYPE': ['fruit', 'fruit', 'vegetable', 'vegetable'],
    'PRICE': [100, 110, 60, 80]
}
raw2_data = {
    'NAME': ['pepper', 'carrot', 'banana', 'kiwi'],
    'TYPE': ['vegetable', 'vegetable', 'fruit', 'fruit'],
    'PRICE': [50, 70, 90, 120]
}
df1 = pd.DataFrame(raw_data , columns=['NAME', 'TYPE', 'PRICE'])
df2 = pd.DataFrame(raw2_data , columns=['NAME', 'TYPE', 'PRICE'])

print(df1, '\n', df2 ,'\n')

df_join = pd.concat([df1, df2])

print(df_join[df_join['TYPE'] == 'fruit']['PRICE'].max() + df_join[df_join['TYPE'] == 'vegetable']['PRICE'].max())

     NAME       TYPE  PRICE
0  cherry      fruit    100
1   mango      fruit    110
2  potato  vegetable     60
3   onion  vegetable     80 
      NAME       TYPE  PRICE
0  pepper  vegetable     50
1  carrot  vegetable     70
2  banana      fruit     90
3    kiwi      fruit    120 

200


In [181]:
import pandas as pd

Sue= [55, 65, 60, 66, 57]
Ryan= [64, 77, 71, 79, 67]
Jay= [88, 81, 79, 89, 77]
Jane= [45, 35, 30, 46, 47]
Anna= [91, 96, 90, 97, 99]

index = ['round_1', 'round_2', 'round_3', 'round_4', 'round_5']

df1 = pd.Series(Sue, index)
df2 = pd.Series(Ryan, index)
df3 = pd.Series(Jay, index)
df4 = pd.Series(Jane, index)
df5 = pd.Series(Anna, index)

df = pd.DataFrame([df1, df2,df3, df4, df5],
        index=['Sue', 'Ryan', 'Jay', 'Jane', 'Anna'])

print(df.describe().loc[['mean', 'max', 'min']])


      round_1  round_2  round_3  round_4  round_5
mean     68.6     70.8     66.0     75.4     69.4
max      91.0     96.0     90.0     97.0     99.0
min      45.0     35.0     30.0     46.0     47.0
